// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pessoa.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Pessoa struct {
	Nome                 string   `protobuf:"bytes,1,opt,name=Nome" json:"Nome,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pessoa) Reset()         { *m = Pessoa{} }
func (m *Pessoa) String() string { return proto.CompactTextString(m) }
func (*Pessoa) ProtoMessage()    {}
func (*Pessoa) Descriptor() ([]byte, []int) {
	return fileDescriptor_pessoa_ffec78c3b26755a8, []int{0}
}
func (m *Pessoa) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pessoa.Unmarshal(m, b)
}
func (m *Pessoa) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pessoa.Marshal(b, m, deterministic)
}
func (dst *Pessoa) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pessoa.Merge(dst, src)
}
func (m *Pessoa) XXX_Size() int {
	return xxx_messageInfo_Pessoa.Size(m)
}
func (m *Pessoa) XXX_DiscardUnknown() {
	xxx_messageInfo_Pessoa.DiscardUnknown(m)
}

var xxx_messageInfo_Pessoa proto.InternalMessageInfo

func (m *Pessoa) GetNome() string {
	if m != nil {
		return m.Nome
	}
	return ""
}

func init() {
	proto.RegisterType((*Pessoa)(nil), "pb.Pessoa")
}

func init() { proto.RegisterFile("pessoa.proto", fileDescriptor_pessoa_ffec78c3b26755a8) }

var fileDescriptor_pessoa_ffec78c3b26755a8 = []byte{
	// 71 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x48, 0x2d, 0x2e,
	0xce, 0x4f, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x92, 0xe1, 0x62,
	0x0b, 0x00, 0x8b, 0x09, 0x09, 0x71, 0xb1, 0xf8, 0xe5, 0xe7, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a,
	0x70, 0x06, 0x81, 0xd9, 0x49, 0x6c, 0x60, 0x85, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x40,
	0x1e, 0x1f, 0x35, 0x38, 0x00, 0x00, 0x00,
}
